name: Cypress Tests

on: push

jobs:
  install-and-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci
      - name: Install Cypress
        run: npm install cypress

  cypress-run:
    runs-on: ubuntu-22.04 # You can use the same or a different environment for each job
    needs: install-and-build # This ensures this job runs only after 'install-and-build' finishes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install Cypress
        run: npm install cypress
      - name: Run cypress tests
        run: npx cypress run
